export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const INCREMENT = 'INCREMENT'

export const APPLY_ARTDATE_FILTER = 'APPLY_DATE_FILTER'
export const APPLY_ARTTITLE_FILTER = 'APPLY_ARTTITLE_FILTER'